version: 2
updates:
  - package-ecosystem: npm
    directory: /aural-api
    schedule: { interval: weekly }
    groups:
      api-dependencies: { patterns: ['*'] }
  - package-ecosystem: npm
    directory: /aural-admin
    schedule: { interval: weekly }
    groups:
      admin-dependencies: { patterns: ['*'] }
  - package-ecosystem: npm
    directory: /aural-website
    schedule: { interval: weekly }
    groups:
      website-dependencies: { patterns: ['*'] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
